### ISSUE TITLE
NoCodeBlockIssue does not match functions with a hinted return type

### ISSUE THREAD

**Issue by gavin-lb** [0Hughman0/pyredditformatbot#3]
Whilst looking at the `NoCodeBlockIssue` validator's pattern in issue #2 I noticed that NoCodeBlockIssue does not match functions with a hinted return type. For example

```
def func() -> bool:
    return True
```

Proposed fix: change the function detection line in the pattern to 

```
            |def\s.*?\(.*?\).*?     # function detection
```
(just add an additional `.*?` after the closing parenthesis but before the colon)

I can write up and submit this as a PR if you want.

**Comment by 0Hughman0** [comment]
Thank you for the suggestion. This is a good point.

Rather than a game of cat and mouse with Python's syntax, I have opted to try and leverage the `ast` library instead.

We will see how that works out, but this should provide a solution to this problem, provided the instance running the bot is using an appropriate version of Python!
