### ISSUE TITLE
Not sure why my post has been flagged?

### ISSUE THREAD

**Issue by proffalken** [0Hughman0/pyredditformatbot#4]
Hi,

Just in case this is some kind of bug, I posted https://www.reddit.com/r/learnpython/comments/u0qqf9/whats_the_best_way_to_load_a_significant_number/i47kurw/?context=3 and used the correct tools in the visual editor to add my code-blocks.

For some reason the bot thinks that I've got python that's unformatted, but I can't see where it is?

**Comment by 0Hughman0** [comment]
Hiya,

Thank you very much for reporting this issue. Indeed there don't seem to be any problems with your post.

Running your posts source against a regex checker, it seems the problem is that the line:

`with sample lines from the file looking like this:`

is setting off the regex for the 'NoCodeBlockIssue` (https://github.com/0Hughman0/pyredditformatbot/blob/master/issues.py#L32)

The fairly crude regex just checks for a new line starting with the word `with` followed by some characters and finishing with a `:`. Which the above line still satisfies.

It's a bit tricky because this line really is valid python code... provided you have defined all those words in 

I am having a think about how best to optimize the formatting detection and if there is a better alternative than regexes. I do think that it's probably impossible to have a 100% accurate detection system.

**Comment by proffalken** [comment]
No worries, glad it was a false positive, I was really scratching my head over that one!
